development:
  adapter: postgresql
  encoding: unicode
  database: rowing_machine_development
  pool: 5
  username: your_username
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rowing_machine_test
  min_messages: WARNING
  pool: 5
  username: your_username
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: rowing_machine_development
  min_messages: WARNING
  pool: 5
  username: your_username
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rowing_machine_development
  pool: 5
  username: your_username
  password: